### ISSUE TITLE
fails to compile on raspbian ven 5 april 2019 13:34

### ISSUE THREAD

**Issue by xevilstar** [TinyMan/node-sylvia#1]
npm install sylvia
(node:4154) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
\
> abstract-socket@2.0.0 install /root/node_modules/sylvia/node_modules/dbus-native/node_modules/abstract-socket
> node-gyp rebuild

make: ingresso nella directory "/root/node_modules/sylvia/node_modules/dbus-native/node_modules/abstract-socket/build"
  CXX(target) Release/obj.target/abstract_socket/src/abstract_socket.o
  SOLINK_MODULE(target) Release/obj.target/abstract_socket.node
  COPY Release/abstract_socket.node
make: uscita dalla directory "/root/node_modules/sylvia/node_modules/dbus-native/node_modules/abstract-socket/build"
npm WARN package.json bcrypt-pbkdf@1.0.1 No repository field.
npm WARN package.json extsprintf@1.0.2 No license field.
npm WARN package.json jsonify@0.0.0 license should be a valid SPDX license expression
npm WARN package.json json-schema@0.2.3 No license field.
npm WARN package.json punycode@1.4.1 punycode is also the name of a node core module.
npm WARN package.json sntp@1.0.9 No license field.
npm WARN package.json string_decoder@1.0.3 string_decoder is also the name of a node core module.
npm WARN package.json verror@1.3.6 No license field.

> speaker@0.3.1 install /root/node_modules/sylvia/node_modules/speaker
> node-gyp rebuild

make: ingresso nella directory "/root/node_modules/sylvia/node_modules/speaker/build"
  CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
../deps/mpg123/src/output/alsa.c:19:28: fatal error: alsa/asoundlib.h: File o directory non esistente
 #include <alsa/asoundlib.h>
                            ^
compilation terminated.
deps/mpg123/output.target.mk:108: set di istruzioni per l'obiettivo "Release/obj.target/output/deps/mpg123/src/output/alsa.o" non riuscito
make: *** [Release/obj.target/output/deps/mpg123/src/output/alsa.o] Errore 1
make: uscita dalla directory "/root/node_modules/sylvia/node_modules/speaker/build"
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.19.30-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/node_modules/sylvia/node_modules/speaker
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> serialport@5.0.0 install /root/node_modules/sylvia/node_modules/serialport
> node-pre-gyp install --fallback-to-build

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/node_modules/sylvia/node_modules/serialport/node_modules/.bin/node-pre-gyp'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! speaker@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the speaker@0.3.1 install script.
npm ERR! This is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.19.30-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "sylvia"
npm ERR! cwd /root
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
root@raspberrypi:~# node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@8.11.1 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /root) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.19.30-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by TinyMan** [comment]
You need to install `libasound2` because sylvia use the npm module `speaker`:

`apt-get install libasound2-dev`
